version: '3.7'

services:
  proxy:
    container_name: proxy.local.com
    image: jwilder/nginx-proxy:latest
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
      - './proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro'
    ports:
      - '80:80'
    restart: unless-stopped
    networks:
      main:
        aliases:
          - proxy.local.com

  api.local.com:
    build: .
    command: bash -c "npm install && npm run start-dev"
    container_name: api.local.com
    depends_on:
      - mongodb.local.com
    volumes:
      - './:/usr/src/app:rw'
    ports:
      - '8080:8080'
    env_file:
      - .env
    networks:
      main:
        aliases:
          - api.local.com

  mongodb.local.com:
    image: mongo:latest
    container_name: mongodb.local.com
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - .data/mongodb:/data/db
    environment:
      VIRTUAL_HOST: mongodb.local.com
    networks:
      main:
        aliases:
          - mongodb.local.com

networks:
  main:
